//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockReplenishment.SqlDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErplyTemp
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ErplyStoreId { get; set; }
        public string ErplyStoreName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
    }
}
