//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockReplenishment.SqlDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public System.DateTimeOffset LogDateTime { get; set; }
        public Nullable<int> TransType { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Message { get; set; }
    }
}
