//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockReplenishment.SqlDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRange
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int RangeId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Range Range { get; set; }
    }
}
