//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockReplenishment.SqlDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public Nullable<System.DateTimeOffset> LastErplyOrderExtractTime { get; set; }
        public Nullable<System.DateTimeOffset> LastOrderCreationTime { get; set; }
        public Nullable<int> NextOrderNo { get; set; }
        public Nullable<int> LastErplyOrderExtractTimeUnix { get; set; }
        public Nullable<int> LastOrderCreationTimeUnix { get; set; }
    }
}
